2024-05-15 05:36:21,586 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:40:21,950 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:41:02,646 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:41:06,294 ERROR: Exception on /user/brandon [GET] [in /home/codespace/.local/lib/python3.10/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/codespace/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/codespace/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/codespace/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/codespace/.local/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/workspaces/cits3403/app/routes.py", line 143, in user
    return render_template('user.html', user=user, games=games)
  File "/home/codespace/.local/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/codespace/.local/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/codespace/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/codespace/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/workspaces/cits3403/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/workspaces/cits3403/app/templates/base.html", line 47, in top-level template code
    {% block content %}{% endblock %}
  File "/workspaces/cits3403/app/templates/user.html", line 18, in block 'content'
    {% include '_post.html' %}
  File "/home/codespace/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/workspaces/cits3403/app/templates/_post.html", line 26, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'.
2024-05-15 05:41:25,426 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:42:54,249 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:46:03,322 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:46:41,375 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:48:04,568 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:50:39,582 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:53:25,812 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:53:28,374 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:53:34,722 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-15 05:53:41,928 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
2024-05-16 03:02:30,979 INFO: Microblog startup [in /workspaces/cits3403/app/__init__.py:46]
