2024-04-24 22:34:20,253 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 15:07:02,601 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 15:24:24,833 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 15:27:21,049 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 15:54:41,549 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 15:56:31,060 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 16:04:45,875 INFO: Microblog startup [in /Users/hoiyensha/rock paper/cits3403/app/__init__.py:46]
2024-04-30 16:05:01,909 ERROR: Exception on / [GET] [in /Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/hoiyensha/rock paper/cits3403/app/routes.py", line 48, in index
    return render_template('index.html', title='Home Page')
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/base.html", line 53, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/index.html", line 10, in block 'content'
    <script src="{{ url_for('scripts', filename='js/app.js') }}"></script>
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/werkzeug/routing/map.py", line 926, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'scripts' with values ['filename']. Did you mean 'register' instead?
2024-04-30 16:05:03,831 ERROR: Exception on /index [GET] [in /Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/hoiyensha/rock paper/cits3403/app/routes.py", line 48, in index
    return render_template('index.html', title='Home Page')
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/base.html", line 53, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/index.html", line 10, in block 'content'
    <script src="{{ url_for('scripts', filename='js/app.js') }}"></script>
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/werkzeug/routing/map.py", line 926, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'scripts' with values ['filename']. Did you mean 'register' instead?
2024-04-30 16:05:05,963 ERROR: Exception on /index [GET] [in /Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/hoiyensha/rock paper/cits3403/app/routes.py", line 48, in index
    return render_template('index.html', title='Home Page')
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/base.html", line 53, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/hoiyensha/rock paper/cits3403/app/templates/index.html", line 10, in block 'content'
    <script src="{{ url_for('scripts', filename='js/app.js') }}"></script>
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1084, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/flask/app.py", line 1073, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/hoiyensha/Library/Python/3.8/lib/python/site-packages/werkzeug/routing/map.py", line 926, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'scripts' with values ['filename']. Did you mean 'register' instead?
